### PR TITLE
removed await in pool query

### PR DESCRIPTION
**Pull request by chaithanyaMarripati**
pool query doesnt return a promise

### CODE REVIEW

**Comment by chaithanyaMarripati** [comment]
closes #6

**Comment by Mayank0255** [comment]
@chaithanyaMarripati Have you tested it out after making the changes?

And can you attach a screenshot after registering a user? I have integrated alerts so it should show a Green colored alert stating something like "User registered"

**Comment by chaithanyaMarripati** [comment]
i have only cloned the backend repo, it should be fine i send the screen shot of server logs ? @Mayank0255

**Comment by chaithanyaMarripati** [comment]
image

does this look good @Mayank0255

**Comment by Mayank0255** [comment]
@chaithanyaMarripati Good job 🎉 🎉

**Pull request merged**
