### PR TITLE
refactor(#2):Refactory tier and first implementation of Sequelize (Model: Tags)

### PR DESCRIPTION
**Pull request by fabioalmeida100**
**Notice:** this PR is an epic. So it's the first implementation of Sequelize and refactory of tiers of the project.

**What was done in this PR?**

- Splited responsibility of model (Repository, only get data and Model for entities)
- Moved some bussines rules to Service tier (for example, create JWT token it isn't responsibility of model, so I moved to service)
- Implementation of Sequelize class
- Implementation first repository with Sequelize (Tags)
- Implementation the relation N-M with Tags and PostTags
- Initial setup of all models in Sequelize of all entities of the project

**What is need for future with Sequelize?**

I recommend split the implementation of Sequelize (because this, I implementation the first entity only in this PR). It's because will be more easy test the conversion of SQL to Sequelize in each PR. 

So, my suggestion for next steps:

- Open a new issue for each other entity that is need to convert SQL to Sequelize in repository (Answers, Posts, Comments, Users)
- After finally all convert of repositories to Sequelize, it's need create the Migrations. Open a PR for it, as well.

### CODE REVIEW

**Comment by fabioalmeida100** [comment]
**Important:** All endpoints was tested before open this PR, but will be good test all operations before merge.

**Comment by Mayank0255** [comment]
@fabioalmeida100 

Okay, so first of all great job!!

1. The splitting up part you said seems fine to me, and I think for that you should create the issues, as it would easier for you to plan and segregate your work. Sounds good?

2. Another proposal I have is that do you I should direct all the PRs of yours to a certain branch, like for say `feature/sequelize`, in which all your PRs related to sequelize and docker will be merged to, in frontend and backend both, and then after the whole docker setup alongwith the complete sequelization is done we can do a major update from `feature/sequelize` to master. What are your thoughts on this?

**Comment by Mayank0255** [comment]
@fabioalmeida100 New branch `feature/sequelize` has been made

**Comment by Mayank0255** [comment]
@fabioalmeida100 

In this step I am getting this

image


After that I used the docker engine to run it from there using the default settings and it got exited instantly and then in the console the error I got was for mysql

image

**Comment by fabioalmeida100** [comment]
You need set up you .env @Mayank0255 . Show me you .env file... But, I think better continue this discuss in PR about Docker implementation...

**Comment by fabioalmeida100** [comment]
> @fabioalmeida100
> 
> Okay, so first of all great job!!
> 
> 1. The splitting up part you said seems fine to me, and I think for that you should create the issues, as it would easier for you to plan and segregate your work. Sounds good?

> 2. Another proposal I have is that do you I should direct all the PRs of yours to a certain branch, like for say `feature/sequelize`, in which all your PRs related to sequelize and docker will be merged to, in frontend and backend both, and then after the whole docker setup alongwith the complete sequelization is done we can do a major update from `feature/sequelize` to master. What are your thoughts on this?

**A1:** for next months I can't work active in this project. My next free period for work active in this project is next year (I guess). So my suggestion is for you go ahead with this implementation (reviews, feedback and merge) and open the issues for other devs help improve the project. The implementation is ready to merge for master (is ready and work fine). 

The refactory was done for make easy next conversion for Sequelize. The next changes will be only each repository (maybe in some models), so it's more easy for next contributes ;-)

**A2:** the implementation of Docker support don't depend on any other implementation. You can go ahead with merge for master if you want.

But, what I think about your suggestion with branch: I think it good for project organization. But, when you create another branch you need more attention for managing the sync in future and conflicts can happen... It's a trade-off that I would not add, because this implementation is ready and don't break the project. 

You can have your project with Sequelize and raw queries, and it works fine. As the project is in evolution, other devs will be improving and convert other queries in other repositories. 

I would do like this!

Ps: I'll follow this PR (reviews and feedback) till finish it.

**Comment by fabioalmeida100** [comment]
This PR close #4, as well :-)

**Comment by fabioalmeida100** [comment]
Opened all issues for convert raw queries to Sequelize:

- https://github.com/Mayank0255/Stackoverflow-Clone-Backend/issues/12
- https://github.com/Mayank0255/Stackoverflow-Clone-Backend/issues/13
- https://github.com/Mayank0255/Stackoverflow-Clone-Backend/issues/14
- https://github.com/Mayank0255/Stackoverflow-Clone-Backend/issues/15

**Ps:** the tags.repository is ready in this PR, here.

**Comment by Mayank0255** [comment]
> You need set up you .env @Mayank0255 . Show me you .env file... But, I think better continue this discuss in PR about Docker implementation...
> 
> This log shows that you don't set up your MySql host correctly.

Sure let's continue this discussion over there

**Comment by Mayank0255** [comment]
> @fabioalmeida100 New branch `feature/sequelize` has been made

@fabioalmeida100 What do you think about this?

**Comment by Mayank0255** [comment]
> > @fabioalmeida100
> > Okay, so first of all great job!!
> > 
> > 1. The splitting up part you said seems fine to me, and I think for that you should create the issues, as it would easier for you to plan and segregate your work. Sounds good?
> 
> > 1. Another proposal I have is that do you I should direct all the PRs of yours to a certain branch, like for say `feature/sequelize`, in which all your PRs related to sequelize and docker will be merged to, in frontend and backend both, and then after the whole docker setup alongwith the complete sequelization is done we can do a major update from `feature/sequelize` to master. What are your thoughts on this?
> 
> **A1:** for next months I can't work active in this project. My next free period for work active in this project is next year (I guess). So my suggestion is for you go ahead with this implementation (reviews, feedback and merge) and open the issues for other devs help improve the project. The implementation is ready to merge for master (is ready and work fine).
> 
> The refactory was done for make easy next conversion for Sequelize. The next changes will be only each repository (maybe in some models), so it's more easy for next contributes ;-)
> 
> **A2:** the implementation of Docker support don't depend on any other implementation. You can go ahead with merge for master if you want.
> 
> But, what I think about your suggestion with branch: I think it good for project organization. But, when you create another branch you need more attention for managing the sync in future and conflicts can happen... It's a trade-off that I would not add, because this implementation is ready and don't break the project.
> 
> You can have your project with Sequelize and raw queries, and it works fine. As the project is in evolution, other devs will be improving and convert other queries in other repositories.
> 
> I would do like this!
> 
> Ps: I'll follow this PR (reviews and feedback) till finish it.

Yes, this makes sense, will then merge this to master directly and then leave the other issues for the complete conversion to me, you and other devs as you said you are not free for a while, so I will remove you as the assignee of those particular split issues you just created so that other devs don't get repelled back.

**Review by Mayank0255 — APPROVED** [review]

**Comment by fabioalmeida100** [comment]
> > > @fabioalmeida100
> > > Okay, so first of all great job!!
> > > 
> > > 1. The splitting up part you said seems fine to me, and I think for that you should create the issues, as it would easier for you to plan and segregate your work. Sounds good?
> > 
> > 
> > > 1. Another proposal I have is that do you I should direct all the PRs of yours to a certain branch, like for say `feature/sequelize`, in which all your PRs related to sequelize and docker will be merged to, in frontend and backend both, and then after the whole docker setup alongwith the complete sequelization is done we can do a major update from `feature/sequelize` to master. What are your thoughts on this?
> > 
> > 
> > **A1:** for next months I can't work active in this project. My next free period for work active in this project is next year (I guess). So my suggestion is for you go ahead with this implementation (reviews, feedback and merge) and open the issues for other devs help improve the project. The implementation is ready to merge for master (is ready and work fine).
> > The refactory was done for make easy next conversion for Sequelize. The next changes will be only each repository (maybe in some models), so it's more easy for next contributes ;-)
> > **A2:** the implementation of Docker support don't depend on any other implementation. You can go ahead with merge for master if you want.
> > But, what I think about your suggestion with branch: I think it good for project organization. But, when you create another branch you need more attention for managing the sync in future and conflicts can happen... It's a trade-off that I would not add, because this implementation is ready and don't break the project.
> > You can have your project with Sequelize and raw queries, and it works fine. As the project is in evolution, other devs will be improving and convert other queries in other repositories.
> > I would do like this!
> > Ps: I'll follow this PR (reviews and feedback) till finish it.
> 
> Yes, this makes sense, will then merge this to master directly and then leave the other issues for the complete conversion to me, you and other devs as you said you are not free for a while, so I will remove you as the assignee of those particular split issues you just created so that other devs don't get repelled back.

Top @Mayank0255 ! You're the best, my friend! Nice man \o/

**Comment by Mayank0255** [comment]
@fabioalmeida100 Haha thanks you are better :D

**Pull request merged**
